### ISSUE TITLE
vue__WEBPACK_IMPORTED_MODULE_34__.createElementVNode) is not a function

### ISSUE THREAD

**Issue by 85636682** [YangJianFei/vue-baidu-map-3x#12]
```
app.js:2680 Uncaught TypeError: (0 , vue__WEBPACK_IMPORTED_MODULE_34__.createElementVNode) is not a function
    at eval (vue-baidu-map-3x.es.js?de10:2973:1)
    at ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js (chunk-vendors.js:1352:1)
    at __webpack_require__ (app.js:2677:33)
    at fn (app.js:2945:21)
    at eval (main.js:19:75)
    at ./src/main.js (app.js:1855:1)
    at __webpack_require__ (app.js:2677:33)
    at app.js:3870:109
    at __webpack_require__.O (app.js:2726:23)
    at app.js:3871:53
```

**Comment by YangJianFei** [comment]
这看不出来哪里有问题，是运行就这样了吗？
把main.js使用的地方截个图看看

**Comment by 85636682** [comment]
我是在单个文件引用方式的
<img width="569" alt="image" src="https://user-images.githubusercontent.com/1079461/193437242-1b59db3e-b9a5-4f53-a194-250ab05a890c.png">
<img width="951" alt="image" src="https://user-images.githubusercontent.com/1079461/193437249-c04fd44a-688f-41d1-ba1a-74875c73d042.png">

**Comment by 85636682** [comment]
```
 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'openBlock' (imported as 'openBlock') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'createElementBlock' (imported as 'createElementBlock') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'normalizeClass' (imported as 'normalizeClass') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'normalizeStyle' (imported as 'normalizeStyle') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'createCommentVNode' (imported as 'createCommentVNode') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'renderSlot' (imported as 'renderSlot') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'withDirectives' (imported as 'withDirectives') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'vShow' (imported as 'vShow') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'resolveComponent' (imported as 'resolveComponent') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'Fragment' (imported as 'Fragment') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'renderList' (imported as 'renderList') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js

export 'createBlock' (imported as 'createBlock') was not found in 'vue' (possible exports: default)

 warning  in ./node_modules/vue-baidu-map-3x/dist/vue-baidu-map-3x.es.js
```

**Comment by 85636682** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/1079461/194822296-e366e510-44b5-4d5a-831c-46c5b46877ed.png">
按照你的方式，还是报一样的错误

**Comment by YangJianFei** [comment]
报错截图截完整点看看
试试把nodemodule删了重新安装试试，还是不行的话微信交流或者用[https://codesandbox.io](https://codesandbox.io)复现一个报错的demo项目我看看。你这个信息太少了
