### ISSUE TITLE
WebGL 使用 bm-polyline 后卡住不能拖拽，不能放大

### ISSUE THREAD

**Issue by Diaosi1111** [YangJianFei/vue-baidu-map-3x#9]
```
getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:20 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'setMinMax')
    at bd.getBoundsIn (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:20:114358)
    at be._initPolyOverLayBasePoint (eval at run (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:122578), <anonymous>:1:183941)
    at be._syncOverlayFromMap (eval at run (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:122578), <anonymous>:1:184899)
    at be._bind (eval at run (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:122578), <anonymous>:1:183569)
    at be._init (eval at run (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:122578), <anonymous>:1:179878)
    at new be (eval at run (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:122578), <anonymous>:1:179824)
    at Array.eval (eval at run (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:122578), <anonymous>:1:183)
    at g0._asyncRegister (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:55351)
    at Array.<anonymous> (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:35238)
    at Function.run (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:122701)
getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:20 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'setMinMax')
    at bd.getBoundsIn (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:20:114358)
    at be._initPolyOverLayBasePoint (eval at run (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:122578), <anonymous>:1:183941)
    at Proxy.eval (eval at run (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:122578), <anonymous>:1:180337)
    at ev.BaseClass.fire.ev.BaseClass.dispatchEvent (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:2632)
    at Proxy.addOverlay (getscript?type=webgl&v=1.0&ak=IDdZzXKwmNj1aHDPKa0uGuy1dhL88ZiB&services=&t=20220830143644:5:37487)
    at Proxy.load (vue-baidu-map-3x.es.js:1423:11)
    at Proxy.ready (vue-baidu-map-3x.es.js:654:14)
    at E$1.emit (vue-baidu-map-3x.es.js:235:20)
    at Object.$emit (vue-baidu-map-3x.es.js:261:32)
    at g0.<anonymous> (vue-baidu-map-3x.es.js:510:19)
```
```vue
<template>
    <bm-marker :position="{lng: point.lng, lat: point.lat}" :dragging="false" lable="{{point.id}}"
        @click="marker_click(point.user_id)">
        <bm-polyline :show="show" :path="paths"></bm-polyline>
    </bm-marker>
</template>

<script setup lang="ts">
import { Point } from '../models/Point';
import { Location } from '../models/Location';
import { BmMarker, BmPolyline } from "vue-baidu-map-3x";
import { Ref } from 'vue';
import Storage from '../service/Storage'

const show = ref(false)
const paths: Ref<Location[]> = ref([])

const marker_click = async (user_id: string) => {
    if (!show.value) {
        paths.value = await Storage.user_all(user_id);
        console.log(paths.value);

        show.value = true;
    }
    else {
        show.value = false;
    }
}

defineProps<{ point: Point }>()
</script>
```

**Comment by Diaosi1111** [comment]
> ```
> <template>
>     <bm-marker :position="{lng: point.lng, lat: point.lat}" :dragging="false" lable="{{point.id}}"
>         @click="marker_click(point.user_id)" />
>     <bm-polyline v-show="show" :path="paths" />
> </template>
> 
> <script setup lang="ts">
> import { Point } from '../models/Point';
> import { Location } from '../models/Location';
> import { BmMarker, BmPolyline } from "vue-baidu-map-3x";
> import { Ref } from 'vue';
> import Storage from '../service/Storage'
> 
> const show = ref(false)
> const paths: Ref<Location[]> = ref([])
> 
> const marker_click = async (user_id: string) => {
>     if (!show.value) {
>         paths.value = await Storage.user_all(user_id);
>         console.log(paths.value);
> 
>         show.value = true;
>     }
>     else {
>         show.value = false;
>     }
> }
> 
> defineProps<{ point: Point }>()
> </script>
> ```
> 
> v-show也没法切换显示与不显示

v-if可以切换，但是 WebGL 下还是不能拖拽和放大

**Comment by YangJianFei** [comment]
> ```
> marker_click
> ```

拖拽和放大是没有这个功能的，如果需要要自己实现。没有提供v-show功能，另外大多组件都没有v-show。
建议加群交流：yjf163163，这里发有时不能及时回复
